### ISSUE TITLE
一個在 iOS Safari 上嘅 bug

### ISSUE THREAD

**Issue by eatradish** [laubonghaudoi/jyutping.org#2]
如圖。（iOS 13.3.1, Safari)
![photo_2020-02-12_00-02-38](https://user-images.githubusercontent.com/19554922/74254422-631d0480-4d2b-11ea-9075-a6a17497c6ba.jpg)

**Comment by eatradish** [comment]
可能你們需要 [normalize.css](https://necolas.github.io/normalize.css/)

**Comment by laubonghaudoi** [comment]
睇唔出來邊度有bug，可唔可以說明下？或者最好直接pull request

**Comment by eatradish** [comment]
睇下裡個視頻，左邊多出咗一條邊。

[IMG_0052.zip](https://github.com/laubonghaudoi/jyutping.org/files/4190003/IMG_0052.zip)

**Comment by laubonghaudoi** [comment]
> 睇下裡個視頻，左邊多出咗一條邊。
> 
> [IMG_0052.zip](https://github.com/laubonghaudoi/jyutping.org/files/4190003/IMG_0052.zip)

但係我喺我嘅 iPhone，加埋瀏覽器模擬器上面都冇呢個問題，會唔會係你用嘅瀏覽器問題？你用嘅係咩手機咩瀏覽器？一唔係你直接 pull request 代碼上來？呢個 bug 我冇得測試修唔到。

**Comment by eatradish** [comment]
> > 睇下裡個視頻，左邊多出咗一條邊。
> > [IMG_0052.zip](https://github.com/laubonghaudoi/jyutping.org/files/4190003/IMG_0052.zip)
> 
> 但係我喺我嘅 iPhone，加埋瀏覽器模擬器上面都冇呢個問題，會唔會係你用嘅瀏覽器問題？你用嘅係咩手機咩瀏覽器？一唔係你直接 pull request 代碼上來？呢個 bug 我冇得測試修唔到。

iPhone SE/iOS 13.3.1/Safari 我盡力試下

**Comment by laubonghaudoi** [comment]
@eatradish 我啱先個 https://github.com/laubonghaudoi/jyutping.org/commit/316be5a436e734f1e873a563b2453bea0dc98109 已經加咗個`normalize.css`，你睇下有冇解決到你嘅問題。

**Comment by eatradish** [comment]
睇嚟無...

**Comment by laubonghaudoi** [comment]
@eatradish 噉我真係冇計嘞，你睇下可唔可以自己下載個hugo準備好開發環境，自己來調試，如果仲係修唔到嘅話就關咗呢個 issue 啦。

**Comment by sgalal** [comment]
@laubonghaudoi 睇來需要識前端開發嘅人幫手

**Comment by laubonghaudoi** [comment]
> @laubonghaudoi 睇來需要識前端開發嘅人幫手

你嘅手機上面有冇呢個問題？而家主要係我個網站係用 hugo 來寫嘅，限制好多，所以可以改嘅空間好細。

**Comment by eatradish** [comment]
我睇到你哋嘅加 normalize.css 嘅方式 https://github.com/laubonghaudoi/jyutping.org/commit/316be5a436e734f1e873a563b2453bea0dc98109 ，好似無成功應用到...

**Comment by eatradish** [comment]
應該直接應用佢哋嘅 css 文件（https://necolas.github.io/normalize.css/8.0.1/normalize.css

**Comment by eatradish** [comment]
發現主題本來就用咗 normalize.css，但系系舊版嘅

**Comment by laubonghaudoi** [comment]
@eatradish 噉應該點樣加？

**Comment by eatradish** [comment]
> @eatradish 噉應該點樣加？

直接喺主題嘅 css 文件引用就好，不過我發現無用，而且我無 macOS 設備調試...

**Comment by laubonghaudoi** [comment]
> > @eatradish 噉應該點樣加？
> 
> 直接喺主題嘅 css 文件引用就好，不過我發現無用，而且我無 macOS 設備調試...

你直接pull request上來？我加完之後你睇下有冇效果。

**Comment by eatradish** [comment]
我喺和嘅 Firefox 上面復現了。
![Screenshot_20200220_163415](https://user-images.githubusercontent.com/19554922/74915449-3178fd00-53ff-11ea-9ad4-85ef535ad029.png)

睇嚟唔關 Safari 嘅事，系咧個按鈕嘅寬度問題

**Comment by laubonghaudoi** [comment]
哦噉就冇計喇，嗰個按鈕位置係模板確定嘅，我都唔識改，或者講要改好麻煩。如果你識改就PR代碼上來，唔得嘅話就唔該你關咗呢個 issue 佢啦，唔該嗮你

**Comment by sgalal** [comment]
新截圖我就睇得明了。

因為 CSS 入邊有

```css
.td-box .row {
    padding-left: 2rem;
    padding-right: 2rem;
}
```

呢兩個 padding 係多餘嘅。

另外，兩粒掣應該加上

```css
white-space: normal;
```

可以保證熒幕過窄（≤ 290px）時文字自動換行，唔似而家頂出熒幕。

**Comment by laubonghaudoi** [comment]
> 新截圖我就睇得明了。
> 
> 因為 CSS 入邊有
> 
> ```css
> .td-box .row {
>     padding-left: 2rem;
>     padding-right: 2rem;
> }
> ```
> 
> 呢兩個 padding 係多餘嘅。
> 
> 另外，兩粒掣應該加上
> 
> ```css
> white-space: normal;
> ```
> 
> 可以保證熒幕過窄（≤ 290px）時文字自動換行，唔似而家頂出熒幕。

我喺我個CSS入邊搵唔到呢行代碼。而且如果真係噉改嘅話，按鈕文字自動換行出來嘅效果會比而家頂出空白更加難睇，確定要噉改？

**Comment by eatradish** [comment]
> > 新截圖我就睇得明了。
> > 因為 CSS 入邊有
> > ```css
> > .td-box .row {
> >     padding-left: 2rem;
> >     padding-right: 2rem;
> > }
> > ```
> > 
> > 
> > 呢兩個 padding 係多餘嘅。
> > 另外，兩粒掣應該加上
> > ```css
> > white-space: normal;
> > ```
> > 
> > 
> > 可以保證熒幕過窄（≤ 290px）時文字自動換行，唔似而家頂出熒幕。
> 
> 我喺我個CSS入邊搵唔到呢行代碼。而且如果真係噉改嘅話，按鈕文字自動換行出來嘅效果會比而家頂出空白更加難睇，確定要噉改？或者講，我有冇辦法將個按鈕居中？

如果只有 iPhone SE 可以復現，可以唔修。

**Comment by laubonghaudoi** [comment]
@eatradish 噉我關閉issue嘞，如果你有興趣修嘅話就直接PR，唔該嗮。
