### ISSUE TITLE
部份內容顯示為簡體

### ISSUE THREAD

**Issue by chaaklau** [laubonghaudoi/jyutping.org#3]
- 語言選「普通話/國語」，「粵語輸入法」嘅「語」字用咗簡體
![image](https://user-images.githubusercontent.com/5143421/77526306-56143900-6ec5-11ea-815c-30261500338e.png)

- 學粵拼版面有同樣情況
![image](https://user-images.githubusercontent.com/5143421/77526396-6fb58080-6ec5-11ea-96f2-5fc4de521af1.png)

**Comment by laubonghaudoi** [comment]
已經修正咗，麻煩再睇下仲有冇其他地方有問題
