### ISSUE TITLE
粵拼韻母 -ing -ung -ik -uk  IPA 標記

### ISSUE THREAD

**Issue by chaaklau** [laubonghaudoi/jyutping.org#4]
以下引用粵拼小組意見
> 建議[ɪ̞] [ʊ̞]改爲[e][o]; 也同[ɵ] 的高低統一起來。

用 [e] [o] 有各種好處，符號標記亦都比較簡單。

**Comment by laubonghaudoi** [comment]
如果改成 [e] 同 [o] 嘅話，噉咪同 ei 嘅 e，仲有 ou入邊嘅 o 一樣？噉會唔會混淆個音位。

**Comment by chaaklau** [comment]
個 argument 係  ou 同 uk, ung 嘅元音係同一個音位，ei 同 ik, ing 嘅元音係同一個音位。

**Comment by laubonghaudoi** [comment]
啱先個更新修正咗，唔該睇下仲有冇問題。然後就係，嗰嗰 eo 究竟應該寫成 [ɵ] 定係 [ø] 好？
